#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running: 
#   (1) You need a "gradle-wrapper.jar" generated by Gradle in /gradle/wrapper
#   (2) If that JAR is missing, this script will fail unless you install Gradle manually.
#   Since this is a generated text response, we assume the environment might have gradle
#   or the JAR is placed manually. For CI, we often rely on setup-gradle actions if JAR is missing.
#
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""

MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* ) cygwin=true ;;
  Darwin* ) darwin=true ;;
  MINGW* ) msys=true ;;
  NONSTOP* ) nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# For the purpose of this file generation, we execute gradle directly if wrapper is missing
# in a real project, the jar must be committed.
if [ ! -f "$CLASSPATH" ]; then
    exec gradle "$@"
fi

javaw_cmd="java"
exec "$javaw_cmd" "$JVM_OPTS" "$JAVA_OPTS" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"